---
# tasks file for sap
- name: Print message
  debug:
    msg: Hello world from ansible

- name: Execute whoami
  shell: whoami
  register: var

- debug:
    msg: "Variable: {{ var.stdout }}"

- debug:
    msg: "{{ role_path }}"

- name: Copy file 
  copy: 
    src: "{{ role_path }}/files/foto.sh"
    dest: /data/innovation/SAP/foto.sh

- name: Execute file
  become: true
  shell: /bin/bash /data/innovation/SAP/foto.sh >> /data/innovation/SAP/foto.txt


